const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 159,
    img: './images/item-1.jpeg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'mutton biryani',
    category: 'lunch',
    price: 259,
    img: 'https://i.ytimg.com/vi/SbWGXcZTYzg/maxresdefault.jpg',
    desc: `Kolkata Biryani is exceptionally light, low on essence and colour, and mildly spiced, rice is steamed with cooked mutton, spices and the much loved browned potatoes `,
  },
  {
    id: 3,
    title: 'Strawberry Milkshake',
    category: 'shakes',
    price: 149,
    img: 'https://b.zmtcdn.com/data/dish_photos/7e9/208c875046c6f6c9ddcdbe8fdf21d7e9.jpg?output-format=webp&fit=around|130:130&crop=130:130;*,*',
    desc: `When we say strawberry, you say yum! Have a swig to know what we mean.`,
  },
  {
    id: 4,
    title: 'Hing Kachori',
    category: 'breakfast',
    price: 50,
    img: 'https://zaykarecipes.com/wp-content/uploads/2018/07/hing-ki-kachori.jpg',
    desc: `Traditionally, the hinger kochuri has a filling made with daals or lentils like urad or chana or toor, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 229,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 189,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Aloo Paratha',
    category: 'breakfast',
    price: 99,
    img: 'https://cdn.cdnparenting.com/articles/2020/01/19152919/Aloo-Paratha-Recipe.jpg',
    desc: ` Aloo parathas consist of unleavened dough rolled with a mixture of mashed potato and spices, which is cooked on a hot tawa with butter or ghee`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 129,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'Oreo MilkShake',
    category: 'shakes',
    price: 299,
    img: 'https://eatingglutenanddairyfree.com/wp-content/uploads/2020/02/EGADFHomemadeoreomilkshake6.jpg',
    desc: `We took the Oreo dunk to the next level! The good old cream and cookie shake now with a rich chocolaty avatar. Prepared with Oreo cookies.`,
  },
  {
    id: 10,
    title: 'English Breakfast',
    category: 'breakfast',
    price: 199,
    img: 'https://media.istockphoto.com/photos/english-breakfast-picture-id641845826?k=6&m=641845826&s=612x612&w=0&h=hkbzoYR2h3G7QDILxXKx8Rnv6HDLEiDxdLznsbLUTZ0=',
    desc: `Traditionally, the hinger kochuri has a filling made with daals or lentils like urad or chana or toor, `,
  },
];
export default menu;
